### ISSUE TITLE
Oeem uploader should take baseline_period_start and reporting_period_end

### ISSUE THREAD

**Issue by philngo** [impactlab/oeem-uploader#17]
At least two fields: baseline_period_start and reporting_period_end, are implied by date of upload and length of consumption, and should be taken care of either in the datastore or in the uploader (and thus should not be columns that are output in the projects csv during the parser ETL step.

**Comment by hunterowens** [comment]
So is this going to occur in the datastore or uploader?

**Comment by philngo** [comment]
I've been thinking about this more and I think that the maybe the most efficient way to handle this would be for the uploader to handle baseline_period_end and reporting_period_start upon initial project creation, and always ignore the fields baseline_period_start and reporting_period_end. We can handle those on the datastore since they're implied by consumption data ranges.

**Comment by hunterowens** [comment]
Ok.
